### PR TITLE
fix: incorrect position Modal component

### LINKED ISSUE #73: 🐞 - incorrect position `Modal` component
### Description

image
Не корректное поведение компонента Modal.
Способ воспроизведения: при открытом sidebar`е вызвать окно modal и скрыть sidebar.

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by TheKenkei**
Closes #73 

https://github.com/routelink/client/assets/100131721/1a80a1f8-8588-476f-b0ad-2bfb670316b7

### CODE REVIEW

File: src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -18,21 +19,25 @@ export function Modal(props: IModal) {
...
-        onClose={props.toggle}>
-        {props.children}
-      </Drawer>
-    </div>
+    <Observer>
+      {() => {
+        return (
+          <Drawer
+            anchor={isMobile ? 'bottom' : 'left'}
+            id="ddd"
```
Comment (olegnowikow) [inline src/components/Modal/Modal.tsx:27]: remove

**Review by olegnowikow — CHANGES_REQUESTED** [review]

**Comment by TheKenkei** [comment]
@olegnowikow, please look at my edits

**Review by olegnowikow — APPROVED** [review]
